name: .NET Core Desktop

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: AspireApp.sln                         # Replace with your solution name
      Test_Project_Path: AspireApp.Web.Tests                 # Replace with your test project path

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core SDK
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # Add MSBuild to the PATH for building .NET Core projects
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name --configuration ${{ matrix.configuration }}

    # Build the application
    - name: Build the application
      run: dotnet build $env:Solution_Name --configuration ${{ matrix.configuration }} --no-restore

    # Run unit tests
    - name: Run unit tests
      run: dotnet test $env:Test_Project_Path --configuration ${{ matrix.configuration }} --no-build --verbosity normal

    # Publish the application
    - name: Publish the application
      run: dotnet publish $env:Solution_Name --configuration ${{ matrix.configuration }} --output ./publish --no-build
